### ISSUE TITLE
App.config and AssemblyInfo.cs missing

### ISSUE THREAD

**Issue by jdphenix** [TheFoxGrounds/VTAG_Core#1]
Upon forking and trying to build, 

> 1>C:\Users\jdphe\source\repos\VTAG_Core\App.config : error MSB3249: Application Configuration file "App.config" is invalid. Could not find file 'C:\Users\jdphe\source\repos\VTAG_Core\App.config'.

I deleted App.config from the project just to see what would happen and got this, 

> 1>CSC : error CS2001: Source file 'C:\Users\jdphe\source\repos\VTAG_Core\Properties\AssemblyInfo.cs' could not be found.

**Comment by TheFoxGrounds** [comment]
Ah, yeah. I'll add it for the purposes of closing this issue, but when this engine is done it'll be released as a DLL, so you won't need the assembly info. :) Please note this is a small project, and incomplete, but if you'd like to give suggestions you're more than welcome to make a pull request

**Comment by TheFoxGrounds** [comment]
Uploaded! if all is well I'll be closing this issue :)
